<div class="menu is-menu-main">
    <p class="menu-label">General</p>
    <ul class="menu-list">
        <li>
            <a href="index.html" class="nav-link has-icon is-active" data-page="dashboard">
                <span class="icon"><i class="fas fa-desktop"></i></span>
                <span class="menu-item-label">Dashboard</span>
            </a>
        </li>
    </ul>
    <p class="menu-label">Examples</p>
    <ul class="menu-list">
        <li>
            <a href="tables.html" class="nav-link has-icon" data-page="test">
                <span class="icon"><i class="fas fa-table"></i></span><!-- class="has-update-mark" -->
                <span class="menu-item-label">Forms and Tables</span>
            </a>
        </li>
        <!--
        <li>
          <a href="forms.html" class="has-icon">
            <span class="icon"><i class="mdi mdi-square-edit-outline"></i></span>
            <span class="menu-item-label">Forms</span>
          </a>
        </li>
        <li>
          <a href="profile.html" class="has-icon">
            <span class="icon"><i class="mdi mdi-account-circle"></i></span>
            <span class="menu-item-label">Profile</span>
          </a>
        </li>
        <li>
          <a class="has-icon has-dropdown-icon">
            <span class="icon"><i class="mdi mdi-view-list"></i></span>
            <span class="menu-item-label">Submenus</span>
            <div class="dropdown-icon">
              <span class="icon"><i class="mdi mdi-plus"></i></span>
            </div>
          </a>
          <ul>
            <li>
              <a href="#void">
                <span>Sub-item One</span>
              </a>
            </li>
            <li>
              <a href="#void">
                <span>Sub-item Two</span>
              </a>
            </li>
            -->
    </ul>
    <p class="menu-label">About</p>
    <ul class="menu-list">
        <!--
        <li>
          <a href="https://admin-one-html.justboil.me/" target="_blank" class="has-icon">
            <span class="icon"><i class="mdi mdi-credit-card-outline"></i></span>
            <span class="menu-item-label">Premium Demo</span>
          </a>
        </li>
        -->
        <li>
            <a href="https://justboil.me/bulma-admin-template/one-html" class="has-icon">
                <span class="icon"><i class="fas fa-info-circle"></i></span>
                <span class="menu-item-label">About</span>
            </a>
        </li>
    </ul>
</div>