<!DOCTYPE html>
<html class="has-aside-left has-aside-mobile-transition has-navbar-fixed-top has-aside-expanded">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dynart Gears</title>
    <?= css('/admin-one/css/main.min.css') ?>
    <?= css('/fontawesome/css/all.min.css') ?>
    <?= css('/main.css') ?>
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Rubik" rel="stylesheet" type="text/css">
    <?= fetch_styles() ?>
</head>
<body>
<div id="app">
    <nav id="navbar-main" class="navbar is-fixed-top">
        <div class="navbar-brand">
            <a class="navbar-item is-hidden-desktop jb-aside-mobile-toggle">
                <span class="icon"><i class="fas fa-bars"></i></span>
            </a>
            <!--
              <div class="navbar-item has-control">
                <div class="control"><input placeholder="Search everywhere..." class="input"></div>
              </div>
            -->
        </div>
        <div class="navbar-brand is-right">
            <a class="navbar-item is-hidden-desktop jb-navbar-menu-toggle" data-target="navbar-menu">
                <span class="icon"><i class="fas fa-ellipsis-v"></i></span>
            </a>
        </div>

        <div class="navbar-menu fadeIn animated faster" id="navbar-menu">
            <div class="navbar-end">
                <!--
              <div class="navbar-item has-dropdown has-dropdown-with-icons has-divider is-hoverable">
                <a class="navbar-link is-arrowless">
                  <span class="icon">
                    <i class="fas fa-bars"></i>
                  </span>
                  <span>Sample Menu</span>
                  <span class="icon">
                    <i class="fas fa-chevron-down"></i>
                  </span>
                </a>
                <div class="navbar-dropdown">
                  <a href="profile.html" class="navbar-item">
                    <span class="icon"><i class="fas fa-user"></i></span>
                    <span>My Profile</span>
                  </a>
                  <a class="navbar-item">
                    <span class="icon"><i class="fas fa-cog"></i></span>
                    <span>Settings</span>
                  </a>
                  <a class="navbar-item">
                    <span class="icon"><i class="fas fa-envelope"></i></span>
                    <span>Messages</span>
                  </a>
                  <hr class="navbar-divider">
                  <a class="navbar-item">
                    <span class="icon"><i class="fas fa-sign-out-alt"></i></span>
                    <span>Log Out</span>
                  </a>
                </div>
              </div>-->
                <div class="navbar-item has-dropdown has-dropdown-with-icons has-divider has-user-avatar is-hoverable">
                    <a class="navbar-link is-arrowless">
                        <div class="is-user-avatar">
                            <img src="https://avatars.dicebear.com/v2/initials/rebecca-bauch.svg" alt="Rebecca Bauch">
                        </div>
                        <div class="is-user-name"><span>Rebecca Bauch</span></div>
                        <span class="icon"><i class="fas fa-chevron-down"></i></span>
                    </a>
                    <div class="navbar-dropdown">
                        <?= $this->fetch(':app/layout-menu-profile') ?>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    <aside class="aside is-placed-left is-expanded">
        <div class="aside-tools"></div>
        <?= $this->fetch(':app/layout-menu') ?>
    </aside>

    <?= $this->fetch(':app/layout-breadcrumb') ?>

    <div id="content">
        <?= fetch_block('content') ?>
    </div>

    <footer class="footer">
        <!--
        <div class="container-fluid">
          <div class="level">
            <div class="level-left">
              <div class="level-item">
                © 2020, JustBoil.me
              </div>
              <div class="level-item">
                <a href="https://github.com/vikdiesel/admin-one-bulma-dashboard" style="height: 20px">
                  <img src="https://img.shields.io/github/v/release/vikdiesel/admin-one-bulma-dashboard?color=%23999">
                </a>
              </div>
            </div>
            <div class="level-right">
              <div class="level-item">
                <div class="logo">
                  <a href="https://justboil.me"><img src="img/justboil-logo.svg" alt="JustBoil.me"></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      -->
    </footer>
</div>

<?= script('/admin-one/js/main.min.js') ?>
<?= script('/jquery-3.6.0.min.js') ?>
<?= script('/gears-app.js') ?>
<?= fetch_scripts() ?>
<script>

// TODO: load from DB

const GearsApp = $('#app').gearsApp({
    'dashboard': {
        url: '<?= route_url('/dashboard') ?>',
        options: {}
    },
    'test': {
        url: '<?= route_url('/test') ?>',
        options: {}
    }
});

</script>

</body>
</html>
