<!-- W3hubs.com - Download Free Responsive Website Layout Templates designed on HTML5 CSS3,Bootstrap which are 100% Mobile friendly. w3Hubs all Layouts are responsive cross browser supported, best quality world class designs. -->
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.css">
    <?= fetch_styles() ?>
    <style type="text/css">
        body{
            padding: 0;
            margin: 0;
        }
        .hero{
            height: 100vh;
            position: relative;
        }
        .notification{
            padding-top: 20px;
            padding-bottom: 30px;
        }
        .button{
            margin-top: 10px;
        }
    </style>
</head>
<body>
<div class="hero is-primary">
    <div class="hero-body">
        <div class="columns is-centered">
            <div class="column is-half">
                <div class="notification is-light">
                    <?= fetch_block('content') ?>
                </div>
            </div>
        </div>
    </div>
    <?= fetch_scripts() ?>
</div>
</body>
</html>