<?php use_layout(':app/layout') ?>
<?php start_block('content') ?>
<div class="page-header">
  <h3 class="page-title">Ajax Test</h3>
</div>
<div class="row">
  <div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <!--<h4 class="card-title">Card title</h4>-->

        <?= $this->fetch(':app/ajax-form', ['form' => $form]) ?>

        <?= $this->fetch(':app/ajax-table') ?>

      </div>
    </div>
  </div>
</div>
<?php end_block() ?>
