<form id="form_<?= $form->getName() ?>">
      <?= $form->fetch() ?>
</form>
<?php append_block('scripts') ?>
<script>
$(function() {

    const submitId = '#test_name8';
    const url = '<?= route_url('ajax-table/process-form') ?>';
    const formName = '<?= $form->getName() ?>';
    const formId = '#form_' + formName;

    // submit form
    $(submitId).click(function(event) {
        event.preventDefault();
        $.ajax({
            url: url,
            method: 'POST',
            contentType: 'application/x-www-form-urlencoded',
            data: $(formId).serialize(),
            success: function(data, status, xhr) {
                data = JSON.parse(data);
                if (data.status == 'error') {
                    Object.entries(data.errors).forEach(entry => {
                        const [name, error] = entry;                        
                        $('#form_input_' + formName + '_' + name + ' .form-error').text(error);
                    });
                } else {
                    // .. show a butterfly! εϊз
                }
                
            }
        })
        
    });

/*
    // text search
    const input = $('#text_search input');
    input.val(options.text);

    let keyUpTimeout = null;
    input.keyup(function() {
        if (keyUpTimeout) {
            clearTimeout(keyUpTimeout);
        }
        keyUpTimeout = setTimeout(function() {
            options.page = 0;
            options.text = input.val();
            //GearsApp.setOptions('ajax-table', options)
            table.refresh();
        }, 300);
    });
*/    

});
</script>
<?php end_block() ?>