<div id="ajax_table">
  <nav><ul class="pagination ajax-table-pager"></ul></nav>                      
  <table class="table is-fullwidth is-striped is-hoverable is-fullwidth">
    <thead></thead>
    <tbody></tbody>
  </table>
</div>
<?php use_script('/jquery.ajax-table.js'); ?>
<?php append_block('scripts') ?>
<script>
$(function() {

    let options = GearsApp.getOptions('ajax-table');
    options.locale = '<?= \Dynart\Minicore\Framework::instance()->get('translation')->getLocale() ?>';

    // ajax table
    const table = $('#ajax_table').ajaxTable('ajax-server.php', options);
    table.createPagerLink = function(page, options) {
        const listItem = $('<li>');
        listItem.addClass(['page-item', page == options.page ? 'active' : '']);
        const link = $('<a>');
        link.addClass('page-link');
        link.text(page + 1);
        listItem.append(link);
        return listItem;
    }

});
</script>
<?php end_block() ?>