<section class="section is-title-bar" style="padding: .6em 1.5em .5em 1.5em">
    <div class="level">
        <div class="level-left">
            <div class="level-item">
                <ul>
                    <li style="font-size: 1em;">Admin</li>
                    <li style="font-size: 1em;">Forms and Tables</li>
                </ul>
            </div>
        </div>
        <!--
        <div class="level-right">
          <div class="level-item">
            <div class="buttons is-right">
              <a href="https://admin-one-html.justboil.me/" target="_blank" class="button is-primary">
                <span class="icon"><i class="mdi mdi-credit-card-outline"></i></span>
                <span>Premium Demo</span>
              </a>
            </div>
          </div>
        </div>
        -->
    </div>
</section>