<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Dynart Gears</title>
<?= css('stellar/vendors/simple-line-icons/css/simple-line-icons.css') ?>
<?= css('stellar/vendors/flag-icon-css/css/flag-icon.min.css') ?>
<?= css('stellar/vendors/css/vendor.bundle.base.css') ?>
<?= css('stellar/css/style.css') ?>
<?= fetch_styles() ?>
<link rel="shortcut icon" href="<?= static_url('stellar/images/favicon.png') ?>">
<style>
.table {
  table-layout: fixed;
}
.table thead th {
  font-weight: bold;
}
.table td {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.breadcrumb {
  padding: 0;
  margin: 0;
}
.navbar .navbar-brand-wrapper .navbar-brand img {
  height: auto;
}
.content-wrapper {
  padding: 1.5rem 1.5rem 0;
}
</style>
</head>
<body>

<div class="container-scroller">
  <!-- navbar -->
  <nav class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    
    <!-- logo -->        
    <div class="navbar-brand-wrapper d-flex align-items-center">
      <a class="navbar-brand brand-logo" href="<?= route_url('') ?>">
        <img src="static/stellar/images/logo.svg" alt="logo" class="logo-dark" />
      </a>
      <a class="navbar-brand brand-logo-mini" href="static/stellar/index.html"><img src="static/stellar/images/logo-mini.svg" alt="logo" /></a>
    </div>

    <!-- menu -->
    <div class="navbar-menu-wrapper d-flex align-items-center flex-grow-1">
      <!--<h5 class="mb-0 font-weight-medium d-none d-lg-flex">Welcome stallar dashboard!</h5>-->
      <nav aria-label="breadcrumb" class="d-md-block">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#">Tables</a></li>
          <li class="breadcrumb-item active" aria-current="page">Basic tables</li>
        </ol>
      </nav>

      <ul class="navbar-nav navbar-nav-right ml-auto">
        <!--
        <form class="search-form d-none d-md-block" action="#">
          <i class="icon-magnifier"></i>
          <input type="search" class="form-control" placeholder="Search Here" title="Search here">
        </form>
        <li class="nav-item"><a href="#" class="nav-link"><i class="icon-basket-loaded"></i></a></li>
        <li class="nav-item"><a href="#" class="nav-link"><i class="icon-chart"></i></a></li>
        -->
        <li class="nav-item dropdown">
          <a class="nav-link count-indicator message-dropdown" id="messageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
            <i class="icon-speech"></i>
            <!--<span class="count">7</span>-->
          </a>
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0" aria-labelledby="messageDropdown">
            <a class="dropdown-item py-3">
              <p class="mb-0 font-weight-medium float-left">You have 7 unread mails </p>
              <span class="badge badge-pill badge-primary float-right">View all</span>
            </a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <img src="static/stellar/images/faces/face10.jpg" alt="image" class="img-sm profile-pic">
              </div>
              <div class="preview-item-content flex-grow py-2">
                <p class="preview-subject ellipsis font-weight-medium text-dark">Marian Garner </p>
                <p class="font-weight-light small-text"> The meeting is cancelled </p>
              </div>
            </a>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <img src="static/stellar/images/faces/face12.jpg" alt="image" class="img-sm profile-pic">
              </div>
              <div class="preview-item-content flex-grow py-2">
                <p class="preview-subject ellipsis font-weight-medium text-dark">David Grey </p>
                <p class="font-weight-light small-text"> The meeting is cancelled </p>
              </div>
            </a>
            <a class="dropdown-item preview-item">
              <div class="preview-thumbnail">
                <img src="static/stellar/images/faces/face1.jpg" alt="image" class="img-sm profile-pic">
              </div>
              <div class="preview-item-content flex-grow py-2">
                <p class="preview-subject ellipsis font-weight-medium text-dark">Travis Jenkins </p>
                <p class="font-weight-light small-text"> The meeting is cancelled </p>
              </div>
            </a>
          </div>
        </li>
        <li class="nav-item dropdown language-dropdown d-none d-sm-flex align-items-center">
          <a class="nav-link d-flex align-items-center dropdown-toggle" id="LanguageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
            <div class="d-inline-flex mr-3">
              <i class="flag-icon flag-icon-hu"></i>
            </div>
            <span class="profile-text font-weight-normal">Magyar</span>
          </a>
          <div class="dropdown-menu dropdown-menu-left navbar-dropdown py-2" aria-labelledby="LanguageDropdown">
            <a class="dropdown-item" id="locale_en">
              <i class="flag-icon flag-icon-us"></i> English</a>
            <a class="dropdown-item" id="locale_hu">
              <i class="flag-icon flag-icon-hu"></i> Magyar</a>
          </div>
        </li>
        <li class="nav-item dropdown d-none d-xl-inline-flex user-dropdown">
          <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
            <img class="img-xs rounded-circle ml-2" src="static/stellar/images/faces/face8.jpg" alt="Profile image"> <span class="font-weight-normal"> TesztJoco </span></a>
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
            <div class="dropdown-header text-center">
              <img class="img-md rounded-circle" src="static/stellar/images/faces/face8.jpg" alt="Profile image">
              <p class="mb-1 mt-3">Teszt József</p>
              <p class="font-weight-light text-muted mb-0">tesztjoszef@gmail.com</p>
            </div>
            <a class="dropdown-item"><i class="dropdown-item-icon icon-user text-primary"></i> My Profile <span class="badge badge-pill badge-danger">1</span></a>
            <a class="dropdown-item"><i class="dropdown-item-icon icon-speech text-primary"></i> Messages</a>
            <a class="dropdown-item"><i class="dropdown-item-icon icon-energy text-primary"></i> Activity</a>
            <a class="dropdown-item"><i class="dropdown-item-icon icon-question text-primary"></i> FAQ</a>
            <a class="dropdown-item"><i class="dropdown-item-icon icon-power text-primary"></i>Sign Out</a>
          </div>
        </li>
      </ul>
      <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
        <span class="icon-menu"></span>
      </button>
    </div>
  </nav>

  <div class="container-fluid page-body-wrapper">
    
    <!-- sidebar -->
    <nav class="sidebar sidebar-offcanvas" id="sidebar">
      <ul class="nav">
        <!--
        <li class="nav-item nav-profile">              
          <a href="#" class="nav-link">
            <div class="profile-image">
              <img class="img-xs rounded-circle" src="static/stellar/images/faces/face8.jpg" alt="profile image">
              <div class="dot-indicator bg-success"></div>
            </div>
            <div class="text-wrapper">
              <p class="profile-name">Allen Moreno</p>
              <p class="designation">Administrator</p>
            </div>
            <div class="icon-container">
              <i class="icon-bubbles"></i>
              <div class="dot-indicator bg-danger"></div>
            </div>
          </a>
        </li>
        -->
        <li class="nav-item nav-category">
          <span class="nav-link">Dashboard</span>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="javascript:void(0)" data-url="<?= route_url('', ['ajax' => 1]) ?>">
            <span class="menu-title">Dashboard</span>
            <i class="icon-screen-desktop menu-icon"></i>
          </a>
        </li>
        <li class="nav-item nav-category"><span class="nav-link">UI Elements</span></li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
            <span class="menu-title">Basic UI Elements</span>
            <i class="icon-layers menu-icon"></i>
          </a>
          <div class="collapse" id="ui-basic">
            <ul class="nav flex-column sub-menu">
              <li class="nav-item"> <a class="nav-link" href="static/stellar/pages/ui-features/buttons.html">Buttons</a></li>
              <li class="nav-item"> <a class="nav-link" href="static/stellar/pages/ui-features/typography.html">Typography</a></li>
            </ul>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="javascript:void(0)" data-url="<?= route_url('ajax-table', ['ajax' => 1]) ?>">
            <span class="menu-title">Ajax Table</span>
            <i class="icon-globe menu-icon"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="static/stellar/pages/forms/basic_elements.html">
            <span class="menu-title">Form Elements</span>
            <i class="icon-book-open menu-icon"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="static/stellar/pages/charts/chartist.html">
            <span class="menu-title">Charts</span>
            <i class="icon-chart menu-icon"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="static/stellar/pages/tables/basic-table.html">
            <span class="menu-title">Tables</span>
            <i class="icon-grid menu-icon"></i>
          </a>
        </li>
        <!--
        <li class="nav-item nav-category"><span class="nav-link">Sample Pages</span></li>            
        <li class="nav-item">
          <a class="nav-link" data-toggle="collapse" href="#auth" aria-expanded="false" aria-controls="auth">
            <span class="menu-title">General Pages</span>
            <i class="icon-doc menu-icon"></i>
          </a>
          <div class="collapse" id="auth">
            <ul class="nav flex-column sub-menu">
              <li class="nav-item"> <a class="nav-link" href="static/stellar/pages/samples/login.html"> Login </a></li>
              <li class="nav-item"> <a class="nav-link" href="static/stellar/pages/samples/register.html"> Register </a></li>
              <li class="nav-item"> <a class="nav-link" href="static/stellar/pages/samples/error-404.html"> 404 </a></li>
              <li class="nav-item"> <a class="nav-link" href="static/stellar/pages/samples/error-500.html"> 500 </a></li>
              <li class="nav-item"> <a class="nav-link" href="static/stellar/pages/samples/blank-page.html"> Blank Page </a></li>
            </ul>
          </div>
        </li>
        -->
      </ul>
    </nav>
    <div class="main-panel">
      <div id="content" class="content-wrapper">

        <?= fetch_block('content') ?>

      </div>
      <footer class="footer">
        <div class="d-sm-flex justify-content-center justify-content-sm-between">
          <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com 2020</span>
          <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin templates</a> from Bootstrapdash.com</span>
        </div>
      </footer>
    </div>
  </div>
</div>
<?= script('jquery-3.6.0.min.js') ?>
<?= script('stellar/vendors/js/vendor.bundle.base.js') ?>
<?= script('stellar/js/off-canvas.js') ?>
<?= script('stellar/js/misc.js') ?>
<?= fetch_scripts() ?>
<script>

const GearsApp = new function() {
    
    const optionsStore = {};

    this.hasOptions = function(name) {
        return optionsStore[name] !== undefined;
    }

    this.getOptions = function(name) {
        if (!this.hasOptions(name)) {
            // TODO: load from DB
            this.setOptions(name, {});
        }
        return optionsStore[name];
    }

    this.setOptions = function(name, options) {
        optionsStore[name] = options;
        // TODO: save to DB
    }
};

// app navigation
$(function() {
    $('.nav-link[data-url]').each(function(i, e) {
        $(e).click(function () {
            $.get($(e).attr('data-url'), function(content) {
                $('#content').html(content);
            });
        });
    });
});

// locale switcher
$(function() {  

    $('#locale_hu').click(function() { setLocale('hu'); });
    $('#locale_en').click(function() { setLocale('en'); });

    function setLocale(locale) {
        options.locale = locale;
        const text = $('#LanguageDropdown span');
        const icon = $('#LanguageDropdown i');
        flag = locale == 'en' ? 'us' : locale;
        icon.removeClass();
        icon.addClass(['flag-icon', 'flag-icon-' + flag]);
        text.text(locale == 'en' ? 'English' : 'Magyar');
        table.refresh();
    }

});
</script>

</body>
</html>