<a href="profile.html" class="navbar-item">
    <span class="icon"><i class="fas fa-user"></i></span>
    <span>My Profile</span>
</a>
<a class="navbar-item">
    <span class="icon"><i class="fas fa-cog"></i></span>
    <span>Settings</span>
</a>
<a class="navbar-item">
    <span class="icon"><i class="fas fa-envelope"></i></span>
    <span>Messages</span>
</a>
<hr class="navbar-divider">
<a class="navbar-item">
    <span class="icon"><i class="fas fa-sign-out-alt"></i></span>
    <span>Log Out</span>
</a>